create table public."Task" (
  id bigint generated by default as identity,
  created_at timestamp with time zone null default now(),
  text text null,
  user_id uuid not null,
  finished boolean null default false,
  constraint Task_pkey primary key (id),
  constraint Task_user_id_fkey foreign key (user_id) references auth.users (id) on delete cascade
) tablespace pg_default;

CREATE POLICY "Enable all for users based on user_id" ON "public"."Task" AS PERMISSIVE FOR ALL TO public USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id)